### ISSUE TITLE
Query Knowrob from CRAM

### ISSUE THREAD

**Issue by JKBehrens** [cram-code/cram_demo#3]
Hello @fairlight1337 and @airballking,

what is your way of interfacing KnowRob from CRAM? I think, the stuff in  [knowrob-utils.lisp](https://github.com/cram-code/cram_demo/blob/master/cram_pr2_fccl_demo/src/knowrob-utils.lisp) show an interesting way. I was wondering, if this is still working and if there is something similar from recent experiments.
I want to query KnowRob for actions, parameters and conditions (which must hold at the beginning and/or during the action execution). Therefore, KnowRob must hold a world state (live logging) and task representation.

Any suggestions? Thank you!

**Comment by fairlight1337** [comment]
Basically what we do is the following:
1. Figure out what you want to know
2. In KnowRob, write a Prolog predicate for it
3. From CRAM, call JSON Prolog directly: `(json-prolog:prolog '("some_predicate" ?a ?b))`

And then interpret the results appropriately. What did you have in mind exactly?

**Comment by airballking** [comment]
@JKBehrens please excuse the late response! Last week's demo was intense, and I think most of us have tried to recover some sleep since then.

Basically, @fairlight1337 described the most convenient way of querying information from Knowrob --both for static knowledge, and dynamically asserted knowledge. The json-prolog interface is stable, has been tested a lot, and is also available for roscpp clients.

Now, the interface for live-asserting facts into Knowrob is less clear. You can (a) use json-prolog and make vanilla assert calls using prolog. That should work, but I am not aware of a bigger demo which did this in our lab. Alternatively (b), `semrec` has a plugin for live-asserting log events into knowrob. That is more convenient if you already use `semrec` for logging in your application. However, we have discovered in recent demos (and last week) that that plugin has room for improvement.
